version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: scripts/init_server
  ApplicationStart:
    - location: scripts/start_server
      runas: ec2-user