version: 0.2

env:
  variables:
    GRADLE_HOME: "/opt/gradle/gradle-5.2.1"
    
phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - apt-get install tree
      - wget https://services.gradle.org/distributions/gradle-5.2.1-bin.zip -P /tmp
      - unzip -d /opt/gradle /tmp/gradle-*.zip

  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd web
      - ./gradlew build
      ## - ./gradlew build -s
      ## - tree .
      - pwd
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
    - buildspec.yml
    - web/build/libs/backendapp-1.0.jar
