version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - apt-get update -y
      - apt-get install -y gradle

  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/backendapp-1.0.jar